#!/usr/bin/env bash

here="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"

cd "$here/_build/html"

if [[ ! -d .git ]]; then
    git init
fi

touch .nojekyll

git add .
git commit -m "Docs"

git push -f git@github.com:vfxetc/vee master:gh-pages
